# Extreme Temperature Events

In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

In [2]:
file_list = os.listdir('../data/temp_events')

In [11]:
len(file_list)

595

In [13]:
file_list[315][:5]

'month'

In [23]:
data = pd.read_csv('../data/temp_events/' + temp_file_list[100]).drop(columns=['Unnamed: 0'])

data

,date,temp_max,temp_min,latitude,longitude,is_above_max_extreme,is_below_min_extreme,is_heat_wave,is_cold_wave
0,2023-02-27,-16.83387,-37.70824,80.0,-40.0,True,False,True,False
1,2023-02-28,-15.28837,-21.99424,80.0,-40.0,True,False,True,False
2,2023-05-14,-28.79577,-33.27808,80.0,-40.0,False,True,False,True
3,2023-05-15,-27.34235,-33.96215,80.0,-40.0,False,True,False,True
4,2023-11-26,-14.74158,-18.16868,80.0,-40.0,True,False,True,False
5,2023-11-27,-13.33310,-21.01310,80.0,-40.0,True,False,True,False

In [8]:
temp_file_list = []

for file in file_list:
    if file[:9] == 'temp_wave':
        temp_file_list.append(file)

In [10]:
len(temp_file_list)

222

In [14]:
mon_file_list = []

for file in file_list:
    if file[:5] == 'month':
        mon_file_list.append(file)

In [16]:
len(mon_file_list)

373

In [32]:
test = pd.read_csv('../data/temp_events/' + temp_file_list[180]).drop(columns=['Unnamed: 0'])

test

,date,temp_max,temp_min,latitude,longitude,is_above_max_extreme,is_below_min_extreme,is_heat_wave,is_cold_wave
0,2021-02-21,-22.45165,-31.61204,50.0,60.0,False,True,False,True
1,2021-02-22,-7.08665,-32.61977,50.0,60.0,False,True,False,True
2,2021-02-25,-21.70254,-31.47707,50.0,60.0,False,True,False,True
3,2021-02-26,-17.15050,-30.80697,50.0,60.0,False,True,False,True
4,2021-03-13,-11.63486,-24.28841,50.0,60.0,False,True,False,True
5,2021-03-14,-10.95002,-25.04532,50.0,60.0,False,True,False,True
6,2021-04-01,0.40300,-11.17585,50.0,60.0,False,True,False,True
7,2021-04-02,2.72775,-9.38633,50.0,60.0,False,True,False,True
8,2022-09-01,34.90664,18.79586,50.0,60.0,True,False,True,False
9,2022-09-02,36.77734,21.30377,50.0,60.0,True,False,True,False
10,2022-09-03,35.11940,18.95266,50.0,60.0,True,False,True,False
11,2023-01-09,-26.10041,-34.95376,50.0,60.0,False,True,False,True
12,2023-01-10,-29.09708,-35.34308,50.0,60.0,False,True,False,True
13,2023-03-27,18.99990,0.00570,50.0,60.0,True,False,True,False
14,2023-03-28,19.69106,1.41110,50.0,60.0,True,False,True,False
15,2023-08-29,14.94125,7.35458,50.0,60.0,False,True,False,True
16,2023-08-30,16.24542,7.40580,50.0,60.0,False,True,False,True
17,2023-12-11,-23.22169,-31.20292,50.0,60.0,False,True,False,True
18,2023-12-12,-26.62174,-31.30636,50.0,60.0,False,True,False,True

In [33]:
data= test

In [57]:
for file in temp_file_list:
    df = pd.read_csv('../data/temp_events/' + file).drop(columns=['Unnamed: 0'])
    if len(df) > 0:
        data = pd.concat([data, df],ignore_index=True)

In [37]:
heat_waves = data[data['is_heat_wave']][['date', 'temp_max', 'temp_min', 'latitude', 'longitude', 'is_heat_wave']]

In [39]:
heat_waves.sort_values(by='date')

          date  temp_max  temp_min  latitude  longitude  is_heat_wave
0   2020-01-04  34.72660  19.35720     -20.0       30.0          True
1   2020-01-05  35.32192  20.07010     -20.0       30.0          True
2   2020-01-06  35.53590  21.57280     -20.0       30.0          True
0   2020-01-06  22.20132  10.06536      30.0      120.0          True
1   2020-01-07  22.82570   3.84054      30.0      120.0          True
..         ...       ...       ...       ...        ...           ...
12  2025-06-11 -31.27434 -39.13580     -88.0     -179.9          True
14  2025-06-26  12.23425   1.75363      70.0      -70.0          True
15  2025-06-27  14.48410   6.35670      70.0      -70.0          True
16  2025-06-28  11.77730   6.36486      70.0      -70.0          True
17  2025-06-29  10.45455   6.81777      70.0      -70.0          True

[1084 rows x 6 columns]

In [58]:
data.to_csv('../data/extreme_temp/extreme_temp_2020_2025.csv')

In [59]:
lat_long = data[['latitude', 'longitude']]

In [60]:
coordinates = lat_long.drop_duplicates(ignore_index=True).apply(np.round)

In [61]:
coordinates.to_csv('../data/extreme_temp/unique_coordinates.csv')

In [67]:
data['month'] = data.apply(lambda row: datetime.date(datetime.fromisoformat(row['date'])).month, axis=1)

In [68]:
data

,date,temp_max,temp_min,latitude,longitude,is_above_max_extreme,is_below_min_extreme,is_heat_wave,is_cold_wave,month
0,2021-02-21,-22.45165,-31.61204,50.0,60.0,False,True,False,True,2
1,2021-02-22,-7.08665,-32.61977,50.0,60.0,False,True,False,True,2
2,2021-02-25,-21.70254,-31.47707,50.0,60.0,False,True,False,True,2
3,2021-02-26,-17.15050,-30.80697,50.0,60.0,False,True,False,True,2
4,2021-03-13,-11.63486,-24.28841,50.0,60.0,False,True,False,True,3
...,...,...,...,...,...,...,...,...,...,...
4946,2022-04-30,24.60113,8.67733,-20.0,30.0,False,True,False,True,4
4947,2022-12-01,23.88186,10.91958,-20.0,30.0,False,True,False,True,12
4948,2022-12-02,27.61004,12.09255,-20.0,30.0,False,True,False,True,12
4949,2024-03-05,34.28573,18.25308,-20.0,30.0,True,False,True,False,3
4950,2024-03-06,35.37838,20.87298,-20.0,30.0,True,False,True,False,3

In [74]:
data['lat_int'] = data.apply(lambda row: int(np.round(row['latitude'])), axis=1)

In [75]:
data['long_int'] = data.apply(lambda row: int(np.round(row['longitude'])), axis=1)

In [76]:
data

,date,temp_max,temp_min,latitude,longitude,is_above_max_extreme,is_below_min_extreme,is_heat_wave,is_cold_wave,month,lat_int,long_int
0,2021-02-21,-22.45165,-31.61204,50.0,60.0,False,True,False,True,2,50,60
1,2021-02-22,-7.08665,-32.61977,50.0,60.0,False,True,False,True,2,50,60
2,2021-02-25,-21.70254,-31.47707,50.0,60.0,False,True,False,True,2,50,60
3,2021-02-26,-17.15050,-30.80697,50.0,60.0,False,True,False,True,2,50,60
4,2021-03-13,-11.63486,-24.28841,50.0,60.0,False,True,False,True,3,50,60
...,...,...,...,...,...,...,...,...,...,...,...,...
4946,2022-04-30,24.60113,8.67733,-20.0,30.0,False,True,False,True,4,-20,30
4947,2022-12-01,23.88186,10.91958,-20.0,30.0,False,True,False,True,12,-20,30
4948,2022-12-02,27.61004,12.09255,-20.0,30.0,False,True,False,True,12,-20,30
4949,2024-03-05,34.28573,18.25308,-20.0,30.0,True,False,True,False,3,-20,30
4950,2024-03-06,35.37838,20.87298,-20.0,30.0,True,False,True,False,3,-20,30

In [77]:
data.to_csv('../data/extreme_temp/extreme_temp_2020_2025.csv')

In [67]:
lat = int(cold_waves.loc[316,'latitude'])
long = int(cold_waves.loc[316,'longitude'])

In [86]:
def extreme_temperature(month, file_name):
    mon_sum = pd.read_csv('../data/temp_events/' + file_name).drop(columns='Unnamed: 0').set_index('month')

    return mon_sum.loc[month, 'max_extreme'], mon_sum.loc[month, 'min_extreme']

In [80]:
extreme_temperature(12, 70, 79)

(7.640740392357074, -50.01099081168861)

In [81]:
data.head()

,date,temp_max,temp_min,latitude,longitude,is_above_max_extreme,is_below_min_extreme,is_heat_wave,is_cold_wave
0,2023-04-28,27.11178,22.84847,0.0,40.0,False,True,False,True
1,2023-04-29,31.02426,22.79043,0.0,40.0,False,True,False,True
2,2021-02-09,-6.49772,-12.82218,50.0,10.0,False,True,False,True
3,2021-02-10,-6.37784,-14.02213,50.0,10.0,False,True,False,True
4,2021-02-11,-2.92155,-13.06684,50.0,10.0,False,True,False,True

In [82]:
data.loc[1723,'date']

'2021-02-08'

In [89]:
data['latitude'].value_counts()

latitude
-80.0    970
 60.0    528
 50.0    468
 40.0    464
 30.0    434
 70.0    362
-70.0    342
-20.0    198
-10.0    188
 20.0    160
 80.0    146
-30.0    118
 10.0     94
 0.0      92
-85.0     48
 52.0     44
-86.0     40
-89.0     30
-79.0     28
-88.0     26
-87.0     26
-84.0     22
-78.0     22
-82.0     22
-90.0     20
-81.0     20
-83.0     14
-50.0      8
Name: count, dtype: int64

In [87]:
df = pd.DataFrame(columns = ['extreme_max', 'extreme_min'])

for i in data.index:
    month = datetime.date(datetime.fromisoformat(data.loc[i,'date'])).month
    lat = int(data.loc[i,'latitude'])
    long = int(data.loc[i,'longitude'])
    
    if f"monthly_summary_lat={lat}_long={long}.csv" in file_list:
        extreme_max, extreme_min = extreme_temperature(month, f"monthly_summary_lat={lat}_long={long}.csv")
    elif f"monthly_summary_lat={lat-1}_long={long}.csv" in file_list:
        extreme_max, extreme_min = extreme_temperature(month, f"monthly_summary_lat={lat}_long={long}.csv")
    elif f"monthly_summary_lat={lat}_long={long-1}.csv" in file_list:
        extreme_max, extreme_min = extreme_temperature(month, f"monthly_summary_lat={lat}_long={long}.csv")
    elif f"monthly_summary_lat={lat-1}_long={long-1}.csv" in file_list:
        extreme_max, extreme_min = extreme_temperature(month, f"monthly_summary_lat={lat}_long={long}.csv")
    else:
        print(f"Can't find the monthly summary file for lat={lat} and long={long}")
        

        
    df.loc[i,'extreme_max'] = extreme_max
    df.loc[i,'extreme_min'] = extreme_min

Can't find the monthly summary file for lat=-80 and long=149
Can't find the monthly summary file for lat=-80 and long=149
Can't find the monthly summary file for lat=-80 and long=149
Can't find the monthly summary file for lat=-80 and long=149
Can't find the monthly summary file for lat=-80 and long=149
Can't find the monthly summary file for lat=-80 and long=149
Can't find the monthly summary file for lat=-80 and long=149
Can't find the monthly summary file for lat=-80 and long=149
Can't find the monthly summary file for lat=-80 and long=149
Can't find the monthly summary file for lat=-80 and long=149
Can't find the monthly summary file for lat=-80 and long=149
Can't find the monthly summary file for lat=-80 and long=149
Can't find the monthly summary file for lat=-80 and long=149
Can't find the monthly summary file for lat=-80 and long=149
Can't find the monthly summary file for lat=-80 and long=149
Can't find the monthly summary file for lat=-80 and long=149
Can't find the monthly summary file for lat=-80 and long=-140
Can't find the monthly summary file for lat=-80 and long=-140
Can't find the monthly summary file for lat=-80 and long=-140
Can't find the monthly summary file for lat=-80 and long=-140
Can't find the monthly summary file for lat=-80 and long=-140
Can't find the monthly summary file for lat=-80 and long=-140
Can't find the monthly summary file for lat=-80 and long=-140
Can't find the monthly summary file for lat=-80 and long=-140
Can't find the monthly summary file for lat=-80 and long=-140
Can't find the monthly summary file for lat=-80 and long=-140
Can't find the monthly summary file for lat=-80 and long=-140
Can't find the monthly summary file for lat=-80 and long=-140
Can't find the monthly summary file for lat=-80 and long=-140
Can't find the monthly summary file for lat=-80 and long=-39
Can't find the monthly summary file for lat=-80 and long=-39
Can't find the monthly summary file for lat=-80 and long=-39
Can't find the monthly summary file for lat=-80 and long=-39
Can't find the monthly summary file for lat=-80 and long=-39
Can't find the monthly summary file for lat=-80 and long=-39
Can't find the monthly summary file for lat=-80 and long=-39
Can't find the monthly summary file for lat=-80 and long=-39
Can't find the monthly summary file for lat=-80 and long=-39
Can't find the monthly summary file for lat=-80 and long=-39
Can't find the monthly summary file for lat=-80 and long=-39
Can't find the monthly summary file for lat=-80 and long=-39
Can't find the monthly summary file for lat=-80 and long=-39
Can't find the monthly summary file for lat=-80 and long=-39
Can't find the monthly summary file for lat=-80 and long=-29
Can't find the monthly summary file for lat=-80 and long=-29
Can't find the monthly summary file for lat=-80 and long=-29
Can't find the monthly summary file for lat=-80 and long=-29
Can't find the monthly summary file for lat=-80 and long=-29
Can't find the monthly summary file for lat=-80 and long=-29
Can't find the monthly summary file for lat=-80 and long=-29
Can't find the monthly summary file for lat=-80 and long=-29
Can't find the monthly summary file for lat=-80 and long=-29
Can't find the monthly summary file for lat=-80 and long=-29
Can't find the monthly summary file for lat=-80 and long=-29
Can't find the monthly summary file for lat=-80 and long=-150
Can't find the monthly summary file for lat=-80 and long=-150
Can't find the monthly summary file for lat=-80 and long=-150
Can't find the monthly summary file for lat=-80 and long=-150
Can't find the monthly summary file for lat=-80 and long=-150
Can't find the monthly summary file for lat=-80 and long=-150
Can't find the monthly summary file for lat=-30 and long=30
Can't find the monthly summary file for lat=-30 and long=30
Can't find the monthly summary file for lat=-30 and long=30
Can't find the monthly summary file for lat=-30 and long=30
Can't find the monthly summary file for lat=-30 and long=30
Can't find the monthly summary file for lat=-30 and long=30
Can't find the monthly summary file for lat=-30 and long=30
Can't find the monthly summary file for lat=-30 and long=30
Can't find the monthly summary file for lat=-30 and long=30
Can't find the monthly summary file for lat=-30 and long=30
Can't find the monthly summary file for lat=-30 and long=30
Can't find the monthly summary file for lat=-30 and long=30
Can't find the monthly summary file for lat=-90 and long=-179
Can't find the monthly summary file for lat=-90 and long=-179
Can't find the monthly summary file for lat=-90 and long=-179
Can't find the monthly summary file for lat=-90 and long=-179
Can't find the monthly summary file for lat=-90 and long=-179
Can't find the monthly summary file for lat=-90 and long=-179
Can't find the monthly summary file for lat=-90 and long=-179
Can't find the monthly summary file for lat=-90 and long=-179
Can't find the monthly summary file for lat=-90 and long=-179
Can't find the monthly summary file for lat=-90 and long=-179
Can't find the monthly summary file for lat=-80 and long=159
Can't find the monthly summary file for lat=-80 and long=159
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-80 and long=0
Can't find the monthly summary file for lat=-30 and long=119
Can't find the monthly summary file for lat=-30 and long=119
Can't find the monthly summary file for lat=-70 and long=89
Can't find the monthly summary file for lat=-70 and long=89
Can't find the monthly summary file for lat=-80 and long=-120
Can't find the monthly summary file for lat=-80 and long=-120
Can't find the monthly summary file for lat=-80 and long=-120
Can't find the monthly summary file for lat=-80 and long=-120
Can't find the monthly summary file for lat=-80 and long=-120
Can't find the monthly summary file for lat=-80 and long=-120
Can't find the monthly summary file for lat=-80 and long=-120
Can't find the monthly summary file for lat=-80 and long=-120
Can't find the monthly summary file for lat=-80 and long=-120
Can't find the monthly summary file for lat=-80 and long=-120
Can't find the monthly summary file for lat=-80 and long=-120
Can't find the monthly summary file for lat=-80 and long=-70
Can't find the monthly summary file for lat=-80 and long=-70
Can't find the monthly summary file for lat=-80 and long=-70
Can't find the monthly summary file for lat=-80 and long=-70
Can't find the monthly summary file for lat=-80 and long=-70
Can't find the monthly summary file for lat=-80 and long=-70
Can't find the monthly summary file for lat=-80 and long=-70
Can't find the monthly summary file for lat=-80 and long=-70
Can't find the monthly summary file for lat=-80 and long=-70
Can't find the monthly summary file for lat=-80 and long=-70
Can't find the monthly summary file for lat=-80 and long=-70
Can't find the monthly summary file for lat=-80 and long=-70
Can't find the monthly summary file for lat=-80 and long=-70
Can't find the monthly summary file for lat=-80 and long=-70
Can't find the monthly summary file for lat=-80 and long=70
Can't find the monthly summary file for lat=-80 and long=70
Can't find the monthly summary file for lat=-80 and long=70
Can't find the monthly summary file for lat=-80 and long=70
Can't find the monthly summary file for lat=-80 and long=70
Can't find the monthly summary file for lat=-80 and long=70
Can't find the monthly summary file for lat=-80 and long=70
Can't find the monthly summary file for lat=-80 and long=70
Can't find the monthly summary file for lat=-80 and long=70
Can't find the monthly summary file for lat=-80 and long=70
Can't find the monthly summary file for lat=-80 and long=70
Can't find the monthly summary file for lat=-80 and long=70
Can't find the monthly summary file for lat=-80 and long=70
Can't find the monthly summary file for lat=-80 and long=70
Can't find the monthly summary file for lat=-80 and long=70
Can't find the monthly summary file for lat=-80 and long=70
Can't find the monthly summary file for lat=-70 and long=119
Can't find the monthly summary file for lat=-70 and long=119
Can't find the monthly summary file for lat=-70 and long=119
Can't find the monthly summary file for lat=-70 and long=119
Can't find the monthly summary file for lat=-70 and long=119
Can't find the monthly summary file for lat=-70 and long=119
Can't find the monthly summary file for lat=-70 and long=119
Can't find the monthly summary file for lat=-70 and long=119
Can't find the monthly summary file for lat=-10 and long=20
Can't find the monthly summary file for lat=-10 and long=20
Can't find the monthly summary file for lat=-10 and long=20
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=129
Can't find the monthly summary file for lat=-80 and long=99
Can't find the monthly summary file for lat=-80 and long=99
Can't find the monthly summary file for lat=-80 and long=99
Can't find the monthly summary file for lat=-80 and long=99
Can't find the monthly summary file for lat=-80 and long=99
Can't find the monthly summary file for lat=-80 and long=99
Can't find the monthly summary file for lat=-80 and long=99
Can't find the monthly summary file for lat=-80 and long=99
Can't find the monthly summary file for lat=-80 and long=99
Can't find the monthly summary file for lat=-80 and long=99
Can't find the monthly summary file for lat=-80 and long=99
Can't find the monthly summary file for lat=-80 and long=99
Can't find the monthly summary file for lat=-80 and long=99
Can't find the monthly summary file for lat=-70 and long=60
Can't find the monthly summary file for lat=-70 and long=60
Can't find the monthly summary file for lat=-70 and long=60
Can't find the monthly summary file for lat=-70 and long=60
Can't find the monthly summary file for lat=-70 and long=60
Can't find the monthly summary file for lat=-70 and long=60
Can't find the monthly summary file for lat=-70 and long=60
Can't find the monthly summary file for lat=-70 and long=60
Can't find the monthly summary file for lat=-70 and long=60
Can't find the monthly summary file for lat=-70 and long=60
Can't find the monthly summary file for lat=-70 and long=60
Can't find the monthly summary file for lat=-70 and long=60
Can't find the monthly summary file for lat=-70 and long=60
Can't find the monthly summary file for lat=-70 and long=60
Can't find the monthly summary file for lat=-70 and long=60
Can't find the monthly summary file for lat=-70 and long=60
Can't find the monthly summary file for lat=-70 and long=60
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-70 and long=70
Can't find the monthly summary file for lat=-80 and long=-9
Can't find the monthly summary file for lat=-80 and long=-9
Can't find the monthly summary file for lat=-80 and long=-9
Can't find the monthly summary file for lat=-80 and long=-9
Can't find the monthly summary file for lat=-80 and long=-9
Can't find the monthly summary file for lat=-80 and long=-9
Can't find the monthly summary file for lat=-80 and long=-9
Can't find the monthly summary file for lat=-80 and long=-9
Can't find the monthly summary file for lat=-80 and long=-9
Can't find the monthly summary file for lat=-80 and long=-9
Can't find the monthly summary file for lat=-80 and long=-9
Can't find the monthly summary file for lat=-10 and long=119
Can't find the monthly summary file for lat=-10 and long=119
Can't find the monthly summary file for lat=-10 and long=119
Can't find the monthly summary file for lat=-10 and long=119
Can't find the monthly summary file for lat=-10 and long=119
Can't find the monthly summary file for lat=-10 and long=119
Can't find the monthly summary file for lat=-10 and long=119
Can't find the monthly summary file for lat=-10 and long=119

FileNotFoundError: [Errno 2] No such file or directory: '../data/temp_events/monthly_summary_lat=52_long=0.csv'

In [4]:
files = os.scandir('../data/temp_events')

In [9]:
len(file_list)

447

In [36]:
test_file = file_list[274]

test_file

'temp_waves_lat=10_long=20.csv'

In [38]:
len(pd.read_csv('../data/temp_events/' + test_file).drop(columns=['Unnamed: 0']))

0

In [31]:
test_file[:9]

'temp_wave'

In [76]:
month_sum = pd.read_csv('../data/temp_events/monthly_summary_lat=70_long=79.csv').drop(columns='Unnamed: 0').set_index('month')

In [77]:
month_sum

       max_extreme  min_extreme
month
1         2.904784   -53.705963
2         7.868182   -49.074396
3         6.563372   -46.298900
4         8.466868   -33.468531
5        12.046267   -16.284997
6        25.551507    -7.549555
7        27.258851    -0.073882
8        26.592989     0.896947
9        17.759182    -7.304653
10       12.156916   -22.871908
11       10.345270   -42.543833
12        7.640740   -50.010991